### ISSUE TITLE
Ability to send raw IRCC commands 

### ISSUE THREAD

**Issue by phillipsnick** [waynehaffenden/node-red-contrib-bravia#1]
Thanks for merging https://github.com/waynehaffenden/bravia/pull/1#issuecomment-301342237

Just trying to work out the best way to integrate support into this module, first issue is naming becomes a little conflicted as we already have `sendIRCC` in this module but serves a different purpose to that of the bravia library. Maybe I could use `sendIRCCValue`?

It would be nice to retain existing support in the IRCC node while adding support for the raw commands. Thoughts on the following approach

* If `msg.payload` is string, retain existing functionality 
* If `msg.payload` is object, expect `name` and/or `value`. If `name` is present then call `node.tv.sendIRCC(codes)`. Else use `value` and pass this onto a potential new method `sendIRCCValue(codes)`?
* `msg.payload` should support arrays of strings/objects (no changes for this seem to be necessary)

**Comment by waynehaffenden** [comment]
Sorry for the delay in getting back to you on this. The only other way we could do it is to "guess" weather the IRCC string was a name or value and based upon this file [https://github.com/shabunin/cf-sonytv/blob/master/scripts/SonyTV.js](https://github.com/shabunin/cf-sonytv/blob/master/scripts/SonyTV.js) it seems that all codes start with 5 capital A's, are 20 characters long and end with a double equals == but whether there are some codes that don't follow this convention I don't know.

I'm happy to merge your changes but wondered what you thought about this approach first?

Wayne

**Comment by phillipsnick** [comment]
Maybe it should support that too? Would make it incredibly flexible in what you throw at it.

Adheres more to NR guidance too then. Kind of makes the objects redundant though. Hmm

```
be forgiving in what types of message properties it accepts.
Message properties can be strings, numbers, booleans, Buffers, objects, arrays or nulls. A node should do The Right Thing when faced with any of these.
```

**Comment by waynehaffenden** [comment]
I'm thinking that the ultimate solution would be to have the one send method as it originally was but with the added logic of determining whether the given code is a name or value using a regex for example. That way it simplifies NR and for users that are less tech-savvy I guess.

Also, could change the NR UI to allow the IRCC codes dropdown as it does now but rather than using that as it's value it copies it to a textbox underneath so that you can override it with a code value instead. It would sadly make your more recent changes redundant though :/

Also, of cause if there are any codes that don't follow that convention!? then it won't work but it does seem (fortunately) like they do?

What do you think?

**Comment by waynehaffenden** [comment]
I've hopefully knocked up the method I described above but as I don't have access to my friends TV at the moment to test, I've put it in this branch: [https://github.com/waynehaffenden/bravia/tree/send-method](https://github.com/waynehaffenden/bravia/tree/send-method).

Do you mind testing this and seeing what you think and if all is good then i'll merge it in, bump the version and then we can work on the NR module?

**Comment by waynehaffenden** [comment]
This is now supported in the latest version.
