### ISSUE TITLE
sending msg.payload

### ISSUE THREAD

**Issue by ins4neuk** [waynehaffenden/node-red-contrib-bravia#5]
Do you have a guide on using the payload option at all. on node red i set a msg.payload to num1,num2,num3 and then pass this onto the bravia node. but the tv will only do what the node is set to for example just send a number 4 or hdmi1 etc. ive also sent the example in the node info and again only sends what is selected. hopefully that makes sense!!

**Comment by waynehaffenden** [comment]
I'm not sure exactly what you mean? The msg.payload takes a string with either a simple command (Name or Value) or multiple delimited by a comma like above. The underlying framework will send the commands in series (one after the other with a slight pause) maybe the TV doesn't like this? I always recommend using the API side of the Bravia TV as this gives you back expected results. Hope this helps.

**Comment by ins4neuk** [comment]
thanks for getting back to me i'll try and explain a little better if i can. i have a msg.payload and i change this to Num1, Num2, Num3 for example. i then pass this over to the bravia node. how ever all it will send is the item that is selected within the node and it will ignore what ever the msg.payload is and just send the node selection. the flow i have below will always just send "8"
![capture](https://user-images.githubusercontent.com/28991053/48986166-433ef800-f109-11e8-8d7c-f8a7c2cf90e8.JPG)

**Comment by ins4neuk** [comment]
Also sorry but i'm struggling on the API side and dont really understand what i need to do or how that even works :(

**Comment by waynehaffenden** [comment]
Ah I completely understand now, if you set the IRCC drop down to nothing or click on the caret icon next to the drop down and when it changes to a textbox leave it blank. The Bravia IRCC node always uses it's own selection over msg.payload so by setting the IRCC code to nothing it will use your payload sent by the previous node.

The API is poorly documented by Sony which isn't helpful but there is documentation out there if you look, unfortunately, since this projects creation I no longer have access to a Sony Bravia TV and therefore I'm unable to test things =(

Please let me know if you need any further help.
