### ISSUE TITLE
Hi, works, but using msg.payload I have an error on deploying node

### ISSUE THREAD

**Issue by Barabba11** [waynehaffenden/node-red-contrib-bravia#6]
Hi, I need to chose one command from the list, but if I chose one it will execute it, not what I pass by msg.payload.
If I want to do so I have to leave the command empty, but doing that I have an error on deply. Works whatever, but annoying. How to overcome it? Thank you

**Comment by waynehaffenden** [comment]
Hi, if you wish to send multiple commands via `msg.payload` then the command dropdown needs to be empty otherwise this will take priority.

**Comment by Barabba11** [comment]
Hi, I send only one command, if I leave the field empty (like I do, the only way to send the msg.payload) I have an error on delploy. Can you please correct it? Thanks

**Comment by waynehaffenden** [comment]
What is the error?

**Comment by Barabba11** [comment]
Hi, I attach the photo, I hope more clear than my words..
http://i66.tinypic.com/110yycw.jpg

**Comment by waynehaffenden** [comment]
Sorry but the picture isn't showing, can you try another image hosting site?

**Comment by Barabba11** [comment]
how not working? It works good.. 
Ok I will 
https://ibb.co/pL4kqwQ
https://imggmi.com/full/2019/1/29/b101818ff234548f835faa0b277816c5-full.jpg.html
https://imgur.com/a/PfauXjN

**Comment by waynehaffenden** [comment]
Thank you, sadly doesn't show what's wrong. Can you take a screen shot of the node settings panel for me please?

**Comment by Barabba11** [comment]
At this moment I can't, the project is stored int the house of my friend, when I'l have access again I can. But really sincerely I don't know why this request, I think the problem is evident in any platform, simply install the latest Node Red, install the module and put it on flow, connect on it an inject node, open its propreties and let the fiels of command blank, or better chose a value from the list and then remove the value by press the edit button. You will have an error as I described.
Unfortunately in ther list there is not "msg.paload" so at least I can chose that value with the peace of Node Red.. wich pretends I specify something there.
I tell you again, it works, yes, using the payload as command, the propblem is only when I deploy, every time I deploy. 
Please include in list msg.payload so we can chose it, thank you

**Comment by waynehaffenden** [comment]
I think you're misunderstanding how to correctly send `msg.payload`, this must be done from a separate node and connected to the input of the Bravia node. You **MUST** then leave the IRCC dropdown as empty for it to use the data passed in from previous node, changing this dropdown to anything other than empty will always use this command over `msg.payload`.

The reason you are receiving an error on deployment is due to something being incorrectly configured within the Bravia node. Please attach as many screenshots of your setup as you can for me to help you further.

Finally, it isn't possible to add `msg.payload` to the IRCC dropdown, it **MUST** be injected through another node to the input of the Bravia node.

**Comment by Barabba11** [comment]
I repeat again, the module is working fine, it accepts msg.payload and transmit it correctly to the TV. I hope this is clear.
The problem is only when I click the button deploy, I have this error that I can ignore, but when you develope the flow and debugging is really annoying to click always to continue. Please fix it.
You can easily 3eproduce the problem, just drag your module to flow, use a command, deploy flow, then try to blank again the field and go deploy again
If it is not clear I'll make you a video

**Comment by waynehaffenden** [comment]
Unfortunately, I'm unable to reproduce the above problem, please send a video as this might help me to deduce what is happening.

**Comment by Barabba11** [comment]
Hi, here is the video.
https://youtu.be/BI-ZVOyIxrc
After rmoving the name I have the error but I can send the comands contained in the payload.
Please remove this error, thanks

**Comment by Barabba11** [comment]
Hi, any news here? You saw the video?
Thanks

**Comment by Barabba11** [comment]
HI, any news? Thanks

**Comment by waynehaffenden** [comment]
Sorry for the delay in getting back to you, I've seen the video, thank you for that, most helpful to see the problem you're having. Unfortunately, I no longer have any access to a Sony Bravia TV since I first developed this and so I'm unable to test or fix the problem. I do have a friend that has this TV so if I'm able to get access to it in anyway then I will come back to you with a solution of some kind.

**Comment by Barabba11** [comment]
thank you! In my opinion ou don't need a tv for fixing it.. it's just a problem of module interface and Node Red, the core code about tv is working fine. You just need to correct the http page I guess, if there is empty value you create something default which not generate the error. Please try it, I'll test it for you
Thanks

**Comment by waynehaffenden** [comment]
I have hopefully fixed the bug where the IRCC field was always required, even when you're planning on injecting it with `msg.payload`. I've published the new module but takes time for Node Red to see the updated package, please test and confirm if this resolves your issue.

**Comment by Barabba11** [comment]
seems all ok, I don't have more the error, I can test it only when I'm back from holidays.
Thank you )

**Comment by waynehaffenden** [comment]
Perfect, glad we got there in the end, sorry it took so look to resolve.
