### ISSUE TITLE
Error Retreiving API Methods / IRCC Codes

### ISSUE THREAD

**Issue by guny74** [waynehaffenden/node-red-contrib-bravia#8]
Hello,

I tried to connect to my Sony Bravia Antroid TV with both Methods (IRCC & AP).
I could connect sucessfully via Rest Api / SOAP API, but if I try to confige 
your nodes I got the error messages :

> Failed to retrieve API methods, check your TV connection settings.

Or 
>Failed to retrieve IRCC codes, check your TV connection settings.

I use port 80, the IP is correct and the PSK also...

The maschine Node red running on, could connect to the TV via port 80....

Where can I find any debug infos or the error ?

Thank you

Regards
  Thorsten

**Comment by waynehaffenden** [comment]
Hi Thorsten,

Unfortunately, I no longer have access to a Sony Bravia TV since I started this project so I have no way of trying to debug this.

This project doesn't do anything with the connection parameters other than pass them through to the other module. I would think that it might be something configured with Node Red that's blocking the connection. Have you tried another node to see if you can connect to the TV (Just any connection to see if it can read data)?

Wayne

**Comment by guny74** [comment]
Hi Wayne,

ok, with an TCP Node i could connect to the TV. 

Which API do you "API" node use ? 

I looked at you code but I could not find which "API or Protocol" you use...

REST API  / Simple IP Commands ?

Regards

**Comment by waynehaffenden** [comment]
Okay, that rules out Node Red being the issue then.

It uses this project also built by me: [https://github.com/waynehaffenden/bravia](https://github.com/waynehaffenden/bravia) and it uses a simple HTTP connection to the REST API.

Would be worth you, writing a simple node program using that module to see if you can connect or not, that will also give you debugging information.

**Comment by guny74** [comment]
Hello,

I tried the some URL Paths from Your Code but I think the API / URLs changed

see
https://pro-bravia.sony.net/develop/index.html

I think If you do not have no Sony TV anymore It would be difficult to correct this.
I decided, that I would use the HTTP Node with the REST API for my three funktions (ON/OFF/ POWERSTATUS).

Thanks.

Regards
   Thorsten

**Comment by waynehaffenden** [comment]
Ah thank you for the link, it does appear they've changed their API since this project was first developed and would no longer work without a re-write which would be near impossible without access to a TV.

Appreciate your time looking into this, I'll update the project to say it's no longer maintained or supported with the latest android release. I'll leave it here for people still using the older API.

**Comment by mja-maia** [comment]
@waynehaffenden was the project closed? I had XBR-55X905E and I had the same problem mentioned above

**Comment by Barabba11** [comment]
Have you 3nabled control on settings?

**Comment by waynehaffenden** [comment]
@mja-maia Please check your connection settings or try using a HTTP Node to rule out that it's not Node Red or the server. Failing that sadly this project is no longer maintained, however, if anyone wants to submit a fix I'll be happy to merge. You'll want to look at the [https://github.com/waynehaffenden/bravia](https://github.com/waynehaffenden/bravia) Bravia project to fix as this package uses that.
